- name: my first play                        
  hosts: all                                 
  become: yes                                                     
  tasks:                                     
    - name:                                  
      debug:                                 
        msg: "hi there this is my first play to be executed on AAP with project integration"
                                                
